on:
  push:
    branches:
    - main
name: deploy minecraft server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          requirements: ./galaxy-requirements.yml
          directory: ./
          key: ${{secrets.ANSIBLE_SSH_KEY}}
          inventory: |
            [smp]
            107.150.36.10
          options: |
            --extra-vars "rcon_password=${{secrets.RCON_PASSWORD}} level_seed=${{secrets.LEVEL_SEED}}"