on:
  push:
    branches:
    - main
name: deploy minecraft server
jobs:
  deploy:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: write ssh private key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./id_ed25519
          contents: ${{ secrets.BACKUP_SSH_PRIVATE_KEY }}
      - name: run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          requirements: ./galaxy-requirements.yml
          directory: ./
          key: ${{secrets.ANSIBLE_SSH_KEY}}
          inventory: |
            [smp]
            107.150.36.10
          options: |
            --extra-vars "rcon_password=${{secrets.RCON_PASSWORD}} level_seed=${{secrets.LEVEL_SEED}} aws_access_key_id=${{secrets.AWS_ACCESS_KEY_ID}} aws_secret_access_key=${{secrets.AWS_SECRET_ACCESS_KEY}} rsync_storage_password=${{secrets.RSYNC_STORAGE_PASSWORD}}"