on:
  push:
    branches:
    - main
name: deploy minecraft server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: lint ansible playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: playbook.yml
      - name: run playbook
        uses: bsdlp/action-ansible-playbook@8e51303cbb76cd0b0cb481947ebaf0e2d056db42
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{secrets.ANSIBLE_SSH_KEY}}
          inventory: |
            [smp]
            107.150.36.10
          options: |
            --extra-vars "rcon_password=${{secrets.RCON_PASSWORD}} level_seed=${{secrets.LEVEL_SEED}}"